### ISSUE TITLE
获客助手怎么授权啊？

### ISSUE THREAD

**Issue by hulang** [jjonline/wx-biz-sdk#1]
`https://developer.work.weixin.qq.com/document/path/99482`
这个玩意。。。

**Comment by jjonline** [comment]
业务授权后，指令回调地址会接收到回调，回调示例example在此：
[https://github.com/jjonline/wx-biz-sdk/blob/17717c249d660dceb7837121e5120f562ac37b03/example/retire_all_command.php#L137](https://github.com/jjonline/wx-biz-sdk/blob/17717c249d660dceb7837121e5120f562ac37b03/example/retire_all_command.php#L137)
